/// AUTOGENERATED FILE. DO NOT EDIT

import 'package:catalog/catalog.dart';
import 'package:flutter/material.dart';
import 'package:example/widgets/body_widget.dart';
import 'dummy/body_widget.dummy.dart';

@Preview(
  id: 'BodyWidgetPreview',
  path: 'widgets/body_widget',
  usesDummies: true,
  dummyParameters: [
    'infoText',
    'counter',
  ],
)
class BodyWidgetPreview extends PreviewWidget {
  const BodyWidgetPreview({super.key});

  @override
  Widget preview(BuildContext context) => BodyWidgetDummy().dummies.isEmpty
      ? Container()
      : ListView(
          children: [
            for (int i = 0; i < BodyWidgetDummy().dummies.length; i++)
              PreviewBoundary(
                dummyBuilder: () => BodyWidgetDummy().dummies[i],
                builder: (BuildContext context, Dummy dummy) {
                  return BodyWidget(
                    infoText: dummy.parameters['infoText'],
                    counter: dummy.parameters['counter'],
                  );
                },
              ),
          ],
        );
}
