/// AUTOGENERATED FILE. DO NOT EDIT

import 'package:catalog/catalog.dart';
import 'package:flutter/material.dart';
import 'package:example/widgets/fab_widget.dart';

@Preview(
  id: 'FabWidgetPreview',
  path: 'widgets/fab_widget',
  description: 'Basic fab widget',
  parameters: {
    'incrementCounter': 'void_function_snackbar',
  },
)
class FabWidgetPreview extends PreviewWidget {
  const FabWidgetPreview({super.key});

  @override
  Widget preview(BuildContext context) => Container(
        constraints: const BoxConstraints(maxWidth: 700),
        child: FabWidget(
          incrementCounter: () {
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(
                duration: Duration(seconds: 2),
                content: Text(
                  'incrementCounter event',
                ),
              ),
            );
          },
        ),
      );
}
