/// AUTOGENERATED FILE. DO NOT EDIT

import 'package:catalog/catalog.dart';
import 'package:flutter/material.dart';
import 'package:example/widgets/main_screen.dart';
import 'dummy/main_screen.dummy.dart';

@Preview(
  id: 'MainScreenPreview',
  path: 'widgets/main_screen_widget',
  usesDummies: true,
  dummyParameters: [
    'title',
    'infoText',
    'counter',
    'incrementCounter',
  ],
)
class MainScreenPreview extends PreviewWidget {
  const MainScreenPreview({super.key});

  @override
  Widget preview(BuildContext context) => MainScreenDummy().dummies.isEmpty
      ? Container()
      : ListView(
          children: [
            for (int i = 0; i < MainScreenDummy().dummies.length; i++)
              PreviewBoundary(
                dummy: MainScreenDummy().dummies[i],
                builder: (BuildContext context, Dummy dummy) {
                  return MainScreen(
                    title: dummy.parameters['title'],
                    infoText: dummy.parameters['infoText'],
                    counter: dummy.parameters['counter'],
                    incrementCounter: dummy.parameters['incrementCounter'],
                  );
                },
              ),
          ],
        );
}
