/// AUTOGENERATED FILE. DO NOT EDIT

import 'package:catalog/catalog.dart';
import 'package:flutter/material.dart';
import 'package:example/widgets/main_screen.dart';
import 'dummy/main_screen.dummy.dart';

@Preview(
  id: 'MainScreenPreview',
  path: 'widgets/main_screen_widget',
  usesDummies: true,
  dummyParameters: [
    'title',
    'infoText',
    'counter',
    'incrementCounter',
  ],
)
class MainScreenPreview extends PreviewWidget {
  const MainScreenPreview({super.key});

  @override
  Widget preview(BuildContext context) => MainScreenDummy().dummies.isEmpty
      ? Container()
      : ListView(
          children: [
            for (int i = 0; i < MainScreenDummy().dummies.length; i++)
              Builder(builder: (context) {
                final dummy = MainScreenDummy().dummies[i];
                final deviceInfo = dummy.deviceInfo;
                if (deviceInfo == null) {
                  return Center(
                    child: Column(
                      children: [
                        Card(
                          clipBehavior: Clip.hardEdge,
                          child: Container(
                            padding: const EdgeInsets.all(15),
                            color: Colors.white,
                            constraints: const BoxConstraints(
                              maxWidth: 400,
                            ),
                            child: Center(child: Text(dummy.description)),
                          ),
                        ),
                        const Padding(
                          padding: EdgeInsets.all(7.5),
                        ),
                        Container(
                          constraints: const BoxConstraints(
                            maxHeight: 700,
                            maxWidth: 700,
                          ),
                          child: Builder(
                            builder: (context) {
                              return Padding(
                                padding: const EdgeInsets.all(15),
                                child: MainScreen(
                                  title: dummy.parameters['title'],
                                  infoText: dummy.parameters['infoText'],
                                  counter: dummy.parameters['counter'],
                                  incrementCounter:
                                      dummy.parameters['incrementCounter'],
                                ),
                              );
                            },
                          ),
                        ),
                      ],
                    ),
                  );
                }

                return Center(
                  child: Container(
                    margin: const EdgeInsets.fromLTRB(15, 15, 15, 25),
                    constraints: const BoxConstraints(
                      maxWidth: 400,
                    ),
                    child: Column(
                      children: [
                        Card(
                          clipBehavior: Clip.hardEdge,
                          child: Container(
                            padding: const EdgeInsets.all(15),
                            color: Colors.white,
                            constraints: const BoxConstraints(
                              maxWidth: 400,
                            ),
                            child: Center(child: Text(dummy.description)),
                          ),
                        ),
                        const Padding(
                          padding: EdgeInsets.all(7.5),
                        ),
                        DeviceFrame(
                          device: deviceInfo,
                          orientation: dummy.orientation,
                          screen: Container(
                            color: dummy.backgroundColor,
                            child: Builder(
                              builder: (context) {
                                return Padding(
                                  padding: const EdgeInsets.all(0),
                                  child: MainScreen(
                                    title: dummy.parameters['title'],
                                    infoText: dummy.parameters['infoText'],
                                    counter: dummy.parameters['counter'],
                                    incrementCounter:
                                        dummy.parameters['incrementCounter'],
                                  ),
                                );
                              },
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                );
              }),
          ],
        );
}
