/// AUTOGENERATED FILE. DO NOT EDIT

/// Launch on Android or iOS as usual.
/// Launch on Web with:
///
/// chromedriver --port=4444
/// flutter drive --driver=test_driver/integration_test.dart --target=integration_test/catalog_widget_integration_test.dart -d chrome

import 'package:integration_test/integration_test.dart';

import 'package:example/widgets/utils/bottom/catalog/integration_test/fab_widget_integration_test.dart'
    as nsyv;
import 'package:example/widgets/other_utils/bottom/catalog/integration_test/warning_info_widget_integration_test.dart'
    as fhuz;
import 'package:example/widgets/screen/catalog/integration_test/sized_container_integration_test.dart'
    as qaip;
import 'package:example/widgets/screen/catalog/integration_test/body_widget_integration_test.dart'
    as afnp;
import 'package:example/widgets/screen/catalog/integration_test/counter_widget_integration_test.dart'
    as mvnf;
import 'package:example/widgets/catalog/integration_test/main_screen_integration_test.dart'
    as gnzn;

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  nsyv.FabWidgetIntegrationTest().main();
  fhuz.WarningInfoWidgetIntegrationTest().main();
  qaip.SizedContainerIntegrationTest().main();
  afnp.BodyWidgetIntegrationTest().main();
  mvnf.CounterWidgetIntegrationTest().main();
  gnzn.MainScreenIntegrationTest().main();
}
