/// AUTOGENERATED FILE. DO NOT EDIT

/// Launch on Android or iOS as usual.
/// Launch on Web with:
///
/// chromedriver --port=4444
/// flutter drive --driver=test_driver/integration_test.dart --target=integration_test/catalog_widget_integration_test.dart -d chrome

import 'package:integration_test/integration_test.dart';

import 'package:example/widgets/utils/bottom/catalog/integration_test/fab_widget_integration_test.dart'
    as fflh;
import 'package:example/widgets/other_utils/bottom/catalog/integration_test/warning_info_widget_integration_test.dart'
    as iuso;
import 'package:example/widgets/screen/catalog/integration_test/sized_container_integration_test.dart'
    as bpok;
import 'package:example/widgets/screen/catalog/integration_test/body_widget_integration_test.dart'
    as dshj;
import 'package:example/widgets/screen/catalog/integration_test/counter_widget_integration_test.dart'
    as ageq;
import 'package:example/widgets/catalog/integration_test/main_screen_integration_test.dart'
    as bbvw;

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  fflh.FabWidgetIntegrationTest().main();
  iuso.WarningInfoWidgetIntegrationTest().main();
  bpok.SizedContainerIntegrationTest().main();
  dshj.BodyWidgetIntegrationTest().main();
  ageq.CounterWidgetIntegrationTest().main();
  bbvw.MainScreenIntegrationTest().main();
}
