/// AUTOGENERATED FILE. DO NOT EDIT

import 'package:example/widgets/utils/bottom/catalog/integration_test/fab_widget_integration_test.dart'
    as zcch;
import 'package:example/widgets/screen/catalog/integration_test/body_widget_integration_test.dart'
    as uetd;
import 'package:example/widgets/screen/catalog/integration_test/counter_widget_integration_test.dart'
    as uoui;
import 'package:example/widgets/catalog/integration_test/main_screen_integration_test.dart'
    as klxv;

void main() {
  zcch.FabWidgetIntegrationTest().main();
  uetd.BodyWidgetIntegrationTest().main();
  uoui.CounterWidgetIntegrationTest().main();
  klxv.MainScreenIntegrationTest().main();
}
