name: example
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  stringcare: ^0.1.7                            # android   ios   linux   macos   web   windows
  catalog:
    path: ../

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk:
      flutter
  flutter_lints: ^5.0.0

stringcare:
  lang:
    obfuscated: "lang"        # obfuscated langs files directory
    original: "lang_base"     # original langs files directory
    test: "lang_test"         # test reveal langs files directory (only needed for testing)
  resources:
    class_name: "R"           # R class for accessing resources
    class_dir: "lib"          # R class directory


catalog:
  base: "lib"
  output: "catalog"
  pageFile: "catalog_component.dart"
  pageRoute: "catalog"
  pageName: "CatalogComponent"
  runtimeConfigHolder: "assets/preview_config.json"
  prefix: "preview"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - lang/
