/// AUTOGENERATED FILE. DO NOT EDIT

import 'package:catalog/catalog.dart';
import 'package:flutter/material.dart';
import 'package:example/widgets/utils/bottom/fab_widget.dart';
import '../dummy/fab_widget.dummy.dart';

@Preview(
  description: 'Basic fab widget',
  parameters: ['incrementCounter'],)
class FabWidgetPreview extends ParentPreviewWidget {
  
  @override
  String get title => 'fab_widget';
  
  @override
  String get basePath => '/catalog';
  
  const FabWidgetPreview({super.key});
    
  @override
  Widget preview(BuildContext context) {
    Catalog().widgetBasicPreviewMap.clear();
    Catalog().widgetDevicePreviewMap.clear();

    if (FabWidgetDummy().dummies.isEmpty) {
      return Container();
    }

    final deviceScreenshotsAvailable =
        FabWidgetDummy().deviceScreenshotsAvailable;
    final screenshotsAvailable = FabWidgetDummy().screenshotsAvailable;

    int basicScreenshots = screenshotsAvailable - deviceScreenshotsAvailable;

    return ListView(
      children: [
        Column(
          children: [
            if (basicScreenshots > 0)
              Center(
                child: Container(
                  constraints: const BoxConstraints(
                    maxWidth: 400,
                  ),
                  child: Card(
                    clipBehavior: Clip.hardEdge,
                    child: Container(
                      padding: const EdgeInsets.all(15),
                      color: Colors.white,
                      child: Row(
                        children: [
                          Expanded(
                            child: Center(
                              child: Text(
                                '$basicScreenshots basic screenshots available',
                              ),
                            ),
                          ),
                          const IconButton(
                            onPressed: processBasicScreenshots,
                            icon: Icon(
                              Icons.screenshot,
                            ),
                          )
                        ],
                      ),
                    ),
                  ),
                ),
              ),
            if (deviceScreenshotsAvailable > 0)
              Center(
                child: Container(
                  constraints: const BoxConstraints(
                    maxWidth: 400,
                  ),
                  child: Card(
                    clipBehavior: Clip.hardEdge,
                    child: Container(
                      padding: const EdgeInsets.all(15),
                      color: Colors.white,
                      child: Row(
                        children: [
                          Expanded(
                            child: Center(
                              child: Text(
                                '$deviceScreenshotsAvailable device screenshots available',
                              ),
                            ),
                          ),
                          const IconButton(
                            onPressed: processDeviceScreenshots,
                            icon: Icon(
                              Icons.screenshot,
                            ),
                          )
                        ],
                      ),
                    ),
                  ),
                ),
              ),
            for (int i = 0; i < FabWidgetDummy().dummies.length; i++)
                PreviewBoundary(
    widgetKey: GlobalKey(),
    dummyBuilder: () => FabWidgetDummy().dummies[i],
    builder: (BuildContext context, Dummy dummy) {
      return FabWidget(incrementCounter: dummy.parameters['incrementCounter'],);
    },
  ),
  
          ],
        )
      ],
    );
  }
  
  
}
    