/// AUTOGENERATED FILE. DO NOT EDIT

import 'package:catalog/catalog.dart';
import 'package:flutter/material.dart';
import 'package:example/widgets/screen/sized_container.dart';
import '../dummy/sized_container.dummy.dart';

@Preview(
  description: 'Container with a max width',
  parameters: ['width', 'child'],
)
class SizedContainerPreview extends ParentPreviewWidget {
  @override
  String get title => 'sized_container';

  @override
  String get basePath => '/catalog';

  const SizedContainerPreview({super.key});

  @override
  Widget preview(BuildContext context) {
    Catalog().widgetBasicPreviewMap.clear();
    Catalog().widgetDevicePreviewMap.clear();

    if (SizedContainerDummy().dummies.isEmpty) {
      return Container();
    }

    final deviceScreenshotsAvailable =
        SizedContainerDummy().deviceScreenshotsAvailable;
    final screenshotsAvailable = SizedContainerDummy().screenshotsAvailable;

    int basicScreenshots = screenshotsAvailable - deviceScreenshotsAvailable;

    return ListView(
      children: [
        Column(
          children: [
            if (basicScreenshots > 0)
              Center(
                child: Container(
                  constraints: const BoxConstraints(
                    maxWidth: 400,
                  ),
                  child: Card(
                    clipBehavior: Clip.hardEdge,
                    child: Container(
                      padding: const EdgeInsets.all(15),
                      color: Colors.white,
                      child: Row(
                        children: [
                          Expanded(
                            child: Center(
                              child: Text(
                                '$basicScreenshots basic screenshots available',
                              ),
                            ),
                          ),
                          const IconButton(
                            onPressed: processBasicScreenshots,
                            icon: Icon(
                              Icons.screenshot,
                            ),
                          )
                        ],
                      ),
                    ),
                  ),
                ),
              ),
            if (deviceScreenshotsAvailable > 0)
              Center(
                child: Container(
                  constraints: const BoxConstraints(
                    maxWidth: 400,
                  ),
                  child: Card(
                    clipBehavior: Clip.hardEdge,
                    child: Container(
                      padding: const EdgeInsets.all(15),
                      color: Colors.white,
                      child: Row(
                        children: [
                          Expanded(
                            child: Center(
                              child: Text(
                                '$deviceScreenshotsAvailable device screenshots available',
                              ),
                            ),
                          ),
                          const IconButton(
                            onPressed: processDeviceScreenshots,
                            icon: Icon(
                              Icons.screenshot,
                            ),
                          )
                        ],
                      ),
                    ),
                  ),
                ),
              ),
            for (int i = 0; i < SizedContainerDummy().dummies.length; i++)
              PreviewBoundary(
                widgetKey: GlobalKey(),
                dummyBuilder: () => SizedContainerDummy().dummies[i],
                builder: (BuildContext context, Dummy dummy) {
                  return buildSizedContainer(dummy);
                },
              ),
          ],
        )
      ],
    );
  }
}

SizedContainer buildSizedContainer(Dummy dummy) {
  return SizedContainer(
    width: dummy.parameters['width'],
    child: dummy.parameters['child'],
  );
}
