/// AUTOGENERATED FILE.
///
/// Use this file for modify the preview of FabWidgetPreview
///

import 'package:catalog/catalog.dart';

class FabWidgetDummy extends PreviewDummy {
  @override
  List<Dummy> get dummies => [
        Dummy(
          parameters: {
            'incrementCounter': () {
              // TODO show snackbar
            },
          },
        ),
      ];
}
