/// AUTOGENERATED FILE.
///
/// Use this file for modify the preview of WarningInfoWidgetPreview
///

import 'package:catalog/catalog.dart';

class WarningInfoWidgetDummy extends PreviewDummy {
  @override
  List<Dummy> get dummies => [
        Dummy(
          parameters: {
            'infoText': 'text sample',
          },
        ),
      ];
}
