/// AUTOGENERATED FILE.
///
/// Use this file for modify the preview of BodyWidgetPreview
///

import 'package:catalog/catalog.dart';

class BodyWidgetDummy extends PreviewDummy {
  @override
  List<Dummy> get dummies => [
        const Dummy(
          parameters: {
            'infoText': 'You have pushed the button this many times:',
            'counter': 0,
          },
        ),
        const Dummy(
          parameters: {
            'infoText':
                'Bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla',
            'counter': 10,
          },
        ),
        const Dummy(
          parameters: {
            'infoText':
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            'counter': 9876,
          },
        ),
        const Dummy(
          parameters: {
            'infoText': 'Other example:',
            'counter': 9999999999999,
          },
        ),
      ];
}
