/// AUTOGENERATED FILE.
///
/// Use this file for modify the preview of MainScreenPreview
///

import 'dart:ui';

import 'package:catalog/catalog.dart';
import 'package:example/r.dart';
import 'package:stringcare/stringcare.dart';

class MainScreenDummy extends PreviewDummy {
  Dummy get baseDummy => Dummy(
    parameters: {
      'title': R.strings.title_app.string(),
      'infoText': R.strings.info_text.string(),
      'incrementCounter': () {
        // nothing to do here
      },
      'counter': 12345,
    },
  );

  @override
  List<Dummy> get dummies => [
        baseDummy.copyWith(
          description: 'iPhone 13 Max main screen',
          device: Device(
            deviceInfo: Devices.ios.iPhone13ProMax,
          ),
          screenshot: Screenshot(
            outputFolder: (Locale? locale) async {
              return 'ios/fastlane/screenshots/${locale?.toLanguageCode() ?? 'en-US'}';
            },
            locales: Stringcare().locales,
            screenshots: [
              IPhone55(
                index: 1,
              ),
              IPhone65(
                index: 1,
              ),
            ],
          ),
        ),
        baseDummy.copyWith(
          description: 'iPad Pro 11 inch Gen 4 main screen',
          device: Device(
            deviceInfo: Devices.ios.iPadPro11Inches,
          ),
          screenshot: Screenshot(
            outputFolder: (Locale? locale) async {
              return 'ios/fastlane/screenshots/${locale?.toLanguageCode() ?? 'en-US'}';
            },
            locales: Stringcare().locales,
            screenshots: [
              IPadPro(
                index: 1,
              ),
              IPadPro3Gen(
                index: 1,
              ),
            ],
          ),
        ),
        baseDummy.copyWith(
          description: 'Samsung Galaxy S20 main screen',
          device: Device(
            deviceInfo: Devices.android.samsungGalaxyS20,
          ),
        ),
      ];
}
