/// AUTOGENERATED FILE.
///
/// Use this file for modify the preview of MainScreenPreview
///

import 'dart:ui';

import 'package:catalog/catalog.dart';

class MainScreenDummy extends PreviewDummy {
  @override
  List<Dummy> get dummies => [
        Dummy(
          device: Device(
            deviceInfo: Devices.ios.iPhone13ProMax,
          ),
          parameters: {
            'title': 'Flutter Demo Home Page',
            'infoText': 'You have pushed the button this many times:',
            'incrementCounter': () {
              // nothing to do here
            },
            'counter': 0,
          },
          description: 'iPhone 13 Max main screen',
          screenshot: Screenshot(
            outputFolder: (Locale? locale) async {
              return 'ios/fastlane/screenshots/${locale?.toLanguageCode()}';
            },
            locales: [
              const Locale('es', 'ES'),
              const Locale('en', 'US'),
              const Locale('en', 'GB'),
              const Locale('fr', 'FR'),
            ],
            screenshots: [
              IPhone55(
                index: 1,
              ),
              IPhone65(
                index: 1,
              ),
              IPadPro(
                index: 1,
              ),
              IPadPro3Gen(
                index: 1,
              ),
            ],
          ),
        ),
        Dummy(
          device: Device(
            deviceInfo: Devices.android.samsungGalaxyS20,
          ),
          parameters: {
            'title': 'Flutter Demo Home Page',
            'infoText': 'You have pushed the button this many times:',
            'incrementCounter': () {
              // nothing to do here
            },
            'counter': 120,
          },
          description: 'Samsung Galaxy S20 main screen',
        ),
      ];
}
