/// AUTOGENERATED FILE.
///
/// Use this file for modify the preview of MainScreenPreview
///

import 'package:catalog/catalog.dart';

class MainScreenDummy extends PreviewDummy {
  @override
  List<Dummy> get dummies => [
        Dummy(
          deviceInfo: Devices.ios.iPhone13ProMax,
          parameters: {
            'title': 'Flutter Demo Home Page',
            'infoText': 'You have pushed the button this many times:',
            'incrementCounter': () {
              // nothing to do here
            },
            'counter': 0,
          },
          description: 'iPhone 13 Max main screen',
        ),
        Dummy(
          deviceInfo: Devices.android.samsungGalaxyS20,
          parameters: {
            'title': 'Flutter Demo Home Page',
            'infoText': 'You have pushed the button this many times:',
            'incrementCounter': () {
              // nothing to do here
            },
            'counter': 120,
          },
          description: 'Samsung Galaxy S20 main screen',
        ),
      ];
}
