/// AUTOGENERATED FILE.
///
/// Use this file to test the widget SizedContainer
///

import 'package:catalog/catalog.dart';
import 'package:flutter/widgets.dart';

import '../dummy/sized_container.dummy.dart';
import '../preview/sized_container.preview.dart';

class SizedContainerTest {
  void main() {
    group(
      'SizedContainer - Tests',
      () {
        testWidgets(
          'Child does not exceed the width',
          (tester) async {
            // prepare the context
            await tester.setupTestContext();

            for (var dummy in SizedContainerDummy().dummies) {
              // prepare the widget
              final widget = buildSizedContainer(dummy);
              await tester.test(widget);

              // get the size of the widget
              final widgetSize = tester.getSize(find.byWidget(widget));

              // check the maximum width
              expect(
                widgetSize.width,
                dummy.parameters['width'],
              );
            }
          },
        );

        testWidgets(
          'Child does exceed the width',
          (tester) async {
            // prepare the context
            await tester.setupTestContext();

            for (var dummy in SizedContainerDummy().dummies) {
              // prepare the widget
              final widget = Container(
                child: dummy.parameters['child'],
              );
              await tester.test(widget);

              // get the size of the widget
              final widgetSize = tester.getSize(find.byWidget(widget));

              // check the maximum width
              expect(
                widgetSize.width,
                greaterThanOrEqualTo(
                  dummy.parameters['width'],
                ),
              );
            }
          },
        );
      },
    );
  }
}
