/// AUTOGENERATED FILE.
///
/// Use this file to test the widget WarningInfoWidget
///

import 'package:catalog/catalog.dart';

import '../dummy/warning_info_widget.dummy.dart';
import '../preview/warning_info_widget.preview.dart';

class WarningInfoWidgetTest {
  void main() {
    group(
      'WarningInfoWidget - Tests',
      () {
        testWidgets(
          'Finds text sample',
          (tester) async {
            final dummy = WarningInfoWidgetDummy().dummies.first;
            final widget = buildWarningInfoWidget(dummy);
            await tester.test(widget);

            expect(find.text('text sample'), findsAny);
          },
        );

        testWidgets(
          'Other lorem text not found',
          (tester) async {
            final dummy = WarningInfoWidgetDummy().dummies.first;
            final widget = buildWarningInfoWidget(dummy);
            await tester.test(widget);

            expect(find.text('ipsu lorem'), findsNothing);
          },
        );
      },
    );
  }
}
