/// AUTOGENERATED FILE.
///
/// Use this file to test the widget BodyWidget
///

import 'package:catalog/catalog.dart';

import '../dummy/body_widget.dummy.dart';
import '../preview/body_widget.preview.dart';

class BodyWidgetIntegrationTest {
  void main() {
    group(
      'BodyWidget - IntegrationTest Tests',
      () {
        testWidgets(
          'Lorem text not found',
          (tester) async {
            final dummy = BodyWidgetDummy().dummies.first;
            final widget = buildBodyWidget(dummy);
            await tester.test(widget);

            expect(find.text('lorem ipsu'), findsNothing);
          },
        );

        testWidgets(
          'Other lorem text not found',
          (tester) async {
            final dummy = BodyWidgetDummy().dummies.first;
            final widget = buildBodyWidget(dummy);
            await tester.test(widget);

            expect(find.text('ipsu lorem'), findsNothing);
          },
        );
      },
    );
  }
}
