/// AUTOGENERATED FILE.
///
/// Use this file to test the widget CounterWidget
///

import 'package:catalog/catalog.dart';

import '../dummy/counter_widget.dummy.dart';
import '../preview/counter_widget.preview.dart';

class CounterWidgetIntegrationTest {
  void main() {
    group(
      'CounterWidget - IntegrationTest Tests',
      () {
        testWidgets(
          'Lorem text not found',
          (tester) async {
            final dummy = CounterWidgetDummy().dummies.first;
            final widget = buildCounterWidget(dummy);
            await tester.test(widget);

            expect(find.text('lorem ipsu'), findsNothing);
          },
        );

        testWidgets(
          'Other lorem text not found',
          (tester) async {
            final dummy = CounterWidgetDummy().dummies.first;
            final widget = buildCounterWidget(dummy);
            await tester.test(widget);

            expect(find.text('ipsu lorem'), findsNothing);
          },
        );
      },
    );
  }
}
