/// AUTOGENERATED FILE.
///
/// Use this file for modify the preview of CounterWidgetPreview
///

import 'package:catalog/catalog.dart';

class CounterWidgetDummy extends PreviewDummy {
  @override
  List<Dummy> get dummies => [
        const Dummy(
          parameters: {
            'counter': 0,
          },
        ),
        const Dummy(
          parameters: {
            'counter': 10,
          },
        ),
        const Dummy(
          parameters: {
            'counter': 9876,
          },
        ),
        const Dummy(
          parameters: {
            'counter': 9999999999999,
          },
        ),
      ];
}
