/// AUTOGENERATED FILE.
///
/// Use this file to prepare the preview and the tests:
///
/// - SizedContainerPreview
/// - SizedContainerTest
/// - SizedContainerIntegrationTest
///

import 'package:catalog/catalog.dart';
import 'package:flutter/widgets.dart';

class SizedContainerDummy extends PreviewDummy {
  @override
  List<Dummy> get dummies => List.generate(
        8,
        (index) => Dummy(
          parameters: {
            'width': (index + 1) * 100.0,
            'child': Text(bigText * 4),
          },
        ),
      );
}
