/// AUTOGENERATED FILE. DO NOT EDIT

import 'package:flutter/material.dart';
import 'package:example/widgets/screen/catalog/preview/counter_widget.preview.dart';

class CounterWidgetPreviewPreviewPageDummy extends StatefulWidget {
  static String routeName = 'counter_widget';

  const CounterWidgetPreviewPreviewPageDummy({super.key});

  @override
  CounterWidgetPreviewPreviewPageDummyState createState() =>
      CounterWidgetPreviewPreviewPageDummyState();
}

class CounterWidgetPreviewPreviewPageDummyState
    extends State<CounterWidgetPreviewPreviewPageDummy> {
  @override
  Widget build(BuildContext context) {
    return const CounterWidgetPreview();
  }
}
