/// AUTOGENERATED FILE. DO NOT EDIT

import 'package:flutter/material.dart';
import 'package:example/widgets/screen/catalog/preview/sized_container.preview.dart';

class SizedContainerPreviewPreviewPageDummy extends StatefulWidget {
  static String routeName = 'sized_container';

  const SizedContainerPreviewPreviewPageDummy({super.key});

  @override
  SizedContainerPreviewPreviewPageDummyState createState() =>
      SizedContainerPreviewPreviewPageDummyState();
}

class SizedContainerPreviewPreviewPageDummyState
    extends State<SizedContainerPreviewPreviewPageDummy> {
  @override
  Widget build(BuildContext context) {
    return const SizedContainerPreview();
  }
}
