/// Autogenerated file. Run the obfuscation command for refresh:
/// 
///      flutter pub run stringcare:obfuscate
/// 

// ignore_for_file: non_constant_identifier_names
class Assets {
  Assets();

  
}

class Strings {
  Strings();

  final String title = 'title';
	final String title_app = 'title_app';
	final String info_text = 'info_text';

}

class R {
  static Assets assets = Assets();
  static Strings strings = Strings();
}
  