/// AUTOGENERATED FILE. DO NOT EDIT

import 'package:flutter/material.dart';
import 'package:example/widgets/other_utils/bottom/catalog/preview/warning_info_widget.preview.dart';

class WarningInfoWidgetPreviewPreviewPageDummy extends StatefulWidget {
  static String routeName = 'warning_info_widget';

  const WarningInfoWidgetPreviewPreviewPageDummy({super.key});

  @override
  WarningInfoWidgetPreviewPreviewPageDummyState createState() =>
      WarningInfoWidgetPreviewPreviewPageDummyState();
}

class WarningInfoWidgetPreviewPreviewPageDummyState
    extends State<WarningInfoWidgetPreviewPreviewPageDummy> {
  @override
  Widget build(BuildContext context) {
    return const WarningInfoWidgetPreview();
  }
}
