/// AUTOGENERATED FILE. DO NOT EDIT

import 'package:example/widgets/utils/bottom/catalog/test/fab_widget_test.dart'
    as xccl;
import 'package:example/widgets/other_utils/bottom/catalog/test/warning_info_widget_test.dart'
    as zvep;
import 'package:example/widgets/screen/catalog/test/sized_container_test.dart'
    as lwnf;
import 'package:example/widgets/screen/catalog/test/body_widget_test.dart'
    as tymo;
import 'package:example/widgets/screen/catalog/test/counter_widget_test.dart'
    as ztou;
import 'package:example/widgets/catalog/test/main_screen_test.dart' as zwdp;

void main() {
  xccl.FabWidgetTest().main();
  zvep.WarningInfoWidgetTest().main();
  lwnf.SizedContainerTest().main();
  tymo.BodyWidgetTest().main();
  ztou.CounterWidgetTest().main();
  zwdp.MainScreenTest().main();
}
