/// AUTOGENERATED FILE. DO NOT EDIT

import 'package:example/widgets/utils/bottom/catalog/test/fab_widget_test.dart'
    as rfnk;
import 'package:example/widgets/other_utils/bottom/catalog/test/warning_info_widget_test.dart'
    as sshj;
import 'package:example/widgets/screen/catalog/test/sized_container_test.dart'
    as tzgw;
import 'package:example/widgets/screen/catalog/test/body_widget_test.dart'
    as bbmy;
import 'package:example/widgets/screen/catalog/test/counter_widget_test.dart'
    as metb;
import 'package:example/widgets/catalog/test/main_screen_test.dart' as lvau;

void main() {
  rfnk.FabWidgetTest().main();
  sshj.WarningInfoWidgetTest().main();
  tzgw.SizedContainerTest().main();
  bbmy.BodyWidgetTest().main();
  metb.CounterWidgetTest().main();
  lvau.MainScreenTest().main();
}
