/// AUTOGENERATED FILE. DO NOT EDIT

import 'package:example/widgets/utils/bottom/catalog/test/fab_widget_test.dart'
    as mxea;
import 'package:example/widgets/other_utils/bottom/catalog/test/warning_info_widget_test.dart'
    as estp;
import 'package:example/widgets/screen/catalog/test/sized_container_test.dart'
    as baxr;
import 'package:example/widgets/screen/catalog/test/body_widget_test.dart'
    as nlha;
import 'package:example/widgets/screen/catalog/test/counter_widget_test.dart'
    as djlm;
import 'package:example/widgets/catalog/test/main_screen_test.dart' as aobt;

void main() {
  mxea.FabWidgetTest().main();
  estp.WarningInfoWidgetTest().main();
  baxr.SizedContainerTest().main();
  nlha.BodyWidgetTest().main();
  djlm.CounterWidgetTest().main();
  aobt.MainScreenTest().main();
}
