/// AUTOGENERATED FILE. DO NOT EDIT

import 'package:flutter/material.dart';
import 'package:example/widgets/utils/bottom/catalog/preview/fab_widget.preview.dart';

class FabWidgetPreviewPreviewPageDummy extends StatefulWidget {
  static String routeName = 'fab_widget';

  const FabWidgetPreviewPreviewPageDummy({super.key});

  @override
  FabWidgetPreviewPreviewPageDummyState createState() =>
      FabWidgetPreviewPreviewPageDummyState();
}

class FabWidgetPreviewPreviewPageDummyState
    extends State<FabWidgetPreviewPreviewPageDummy> {
  @override
  Widget build(BuildContext context) {
    return const FabWidgetPreview();
  }
}
