/// AUTOGENERATED FILE.
///
/// Use this file for testing the widget FabWidgetPreview
///

import 'package:catalog/catalog.dart';

import '../../fab_widget.dart';
import '../dummy/fab_widget.dummy.dart';

class FabWidgetTest {
  void main() {
    group(
      'FabWidget - Tests',
      () {
        testWidgets(
          'Lorem text not found',
              (tester) async {
            final dummy = FabWidgetDummy().dummies.first;

            final widget = FabWidget(
              incrementCounter: dummy.parameters['incrementCounter'],
            );

            await tester.test(widget);

            expect(find.text('lorem ipsu'), findsNothing);
          },
        );

        testWidgets(
          'Other lorem text not found',
              (tester) async {
            final dummy = FabWidgetDummy().dummies.first;

            final widget = FabWidget(
              incrementCounter: dummy.parameters['incrementCounter'],
            );

            await tester.test(widget);

            expect(find.text('lorem ipsu'), findsNothing);
          },
        );
      },
    );
  }
}
