/// AUTOGENERATED FILE. DO NOT EDIT

import 'package:flutter/material.dart';
import 'package:example/widgets/catalog/preview/main_screen.preview.dart';

class MainScreenPreviewPreviewPageDummy extends StatefulWidget {

  static String routeName = 'main_screen';
  
  const MainScreenPreviewPreviewPageDummy({super.key});

  @override
  MainScreenPreviewPreviewPageDummyState createState() => MainScreenPreviewPreviewPageDummyState();
}

class MainScreenPreviewPreviewPageDummyState extends State<MainScreenPreviewPreviewPageDummy> {
  @override
  Widget build(BuildContext context) {
    return const MainScreenPreview();
  }
}
    